
---
title: 'Programming Basics and Best Practices'
output:
  slidy_presentation: default
  ioslides_presentation: default
  beamer_presentation: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Protocols and Guidance on how to best use this class

*  Learning to program is hard and I may not always explain in a way that is accessible to you - So if you don't understand something *ASK* , you will help me to learn how to explain (or find an answer if I don't know it) and you will help others

* Programming gets better with practice and play - Don't just read the Rmarkdown - try the code, try variations on the ideas presented, make up stuff to try, get your feet wet 

* Programming means making mistakes, expect it, stay calm and try again - if you get frustrated step away and come back; be creative


* Support each other 
  * when working in groups, pay attention to your partner, if they are not at your skill level, help them learn - recognize that we all have different backgrounds
  * always treat each other with respect - everyone is learning
  
* Break tasks down in steps - start with what you can do

* If you are really struggling, reach out to Ojas or myself, we can help
(or if you just want to chat about something ) 

# Getting help

Ask - each other, in class, in office hours....

**ChatGPT**

* really useful tool, but much more useful if you ask good questions - so you need to have the basic framework/idea in your head

* trying to code yourself, builds that framework

* encourage you to use for syntax (e.g in *ggplot* how do I change the axis font), but not for whole assignment (e.g. write a function to estimate population growth)

* always read through answer and make sure it *makes sense* (does what you were asking)


# What we will learn - some  more details

* Modular programming: Designing building blocks or functions

* Data structures, operations and flow control (general programmings skills we use for manipulating data inside each block)

* Automated (or semi-automated) Tools for good programming practice
  * testing
  * documentation
  * workflow for sharing programs/packages with others
  

The course features **R** for programming, **Git** for version control, **Markdown** for workflow, and **GitHub** for collaboration and publishing, but many concepts would be applicable in other software design tools.




# What is a program

* A program is a set of instructions for a computer to follow
* Programs are often used to manipulate data (in all type and formats you discussed last week)
* Simple to complex

    + scripts that you save in R-Markdown
    + instructions to analyze relationships in census data and visualize them
    + a model of global climate

# BREAKOUT GROUP TASK:
 
* If you haven't already, download climate.csv and load into R
* In an R-markdown document, write R code that does something interesting with the data (this is your first program in the course)

 
# Programming Languages

* Programs can be written in many different languages (all have their strengths and weakness)
* Languages expect instructions in a particular form (syntax) and then translate them to be readable by the computer
* Languages have evolved to make it help users write programs that are easy to understand, re-use, extend, test, run quickly, use lots of data...

# Programming Fundamentals - "Big Ideas"

* Data structures (simple variables, arrays, lists...) - how do we organize data
*  Basic Operations (=,+,-,...concatenate, copy)  to Control structures (if then, loops) - how do we manipulate data
* Modules...Functions - how do we make all this efficient - especially when we want to similar types of things over an over

These concepts common to all languages through the syntax may be different




# BREAKOUT GROUP TASK:
  Based on whatever programming/coding experience you have had - come up with what you think are 4 best practices
 

  
# Best Practices for Software Development 


* Wilson G, Aruliah DA, Brown CT, Chue Hong NP, Davis M, et al. (2014) Best Practices for Scientific Computing. PLoS Biol 12(1): e1001745. doi:10.1371/journal.pbio.1001745

*  Blanton, B and Lenhardt, C 2014. A Scientist’s Perspective on Sustainable Scientific Software. Journal of Open Research Software 2(1):e17, DOI: http://dx.doi.org/10.5334/jors.ba

[Alternative View](http://simpleprogrammer.com/2013/02/17/principles-are-timeless-best-practices-are-fads/)

# Summary of Best Practices

[Wilson et al, Summary Box](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745#pbio-1001745-box001)
  

# Common Coding/Software Engineering Issues

* Unreadable code (hard to understand, easy to forget how it works, hard to find errors, hard to expand)
* Overly complex, disorganized code (hard to find errors; hard to modify-expand)
* Insufficient testing (both during development and after)
* Not tracking code changes (multiple versions, which is correct?)


# Automated Tools for Best Practices in Software Engineering

Automated tools (really useful for more complex code development
( note that GP’s often create programs > 100 lines of code)

Automated documentation

http://www.stack.nl/~dimitri/doxygen/

http://roxygen.org/roxygen2-manual.pdf 

Automated test case development

http://r-pkgs.had.co.nz/tests.html


Automated code evolution tracking (Version Control)
https://github.com/


