---
title: "Assignments"
---


# Assignment materials and dates

|Week| Name.  | Assigned   | Due date   | Group | 
|....|--------|------------|------------|-------|
| 1 |Modular Design | 2025-02-13 | 2025-02-17 | G |
| 2 |Making a function   | 2025-02-18 | 2025-02-24 | I |
| 3 |Using Git with your function   | 2025-02-25 | 2025-03-03 | I |
| 4 |Looping   | 2025-03-4 | 2025-03-10 | I |
| 5 |Functions with lists and testing | 2025-3-11| 2025-3-18 | G |


# Assignment expectations and grading

- All assignments submitted on Canvas
- Late Assignments 10% each day. Try to submit on time as we build on the concepts and materials covered in each assignment
- Style counts; So make sure your follow good programming practices including adding documentation and using informative variable names
- You can use AI (ChatGPT etc) to help you learn syntax, but write the code yourself; this is how you learn
- You can resubmit your assignment for additional feedback and we will upgrade your grade. Please do so with in one week of getting the assignment back


