---
title: "Assignment 5"

---

# Assignment 4
For this assignment work in pairs - and submit as a group

* Design a function - you can pick anything - and you can essentially make up the equations as long as they conceptually make sense
Make sure it has at least 2 inputs and 1 parameter (ideally more)

* Code your function in R, save as a R file in subdirectory called R
Make sure you include documentation (both at the top as we've shown in past examples, and inline)
Include some error checking

* In an Rmarkdown file, generate some data for 2 of the function inputs, 
use a for  loop to run the function for the data 
repeat the "looping" using something from the "purrr" package 

* Graph the result (you can decide what the most interesting way to graph is)

* Include your function.R file, and the Rmarkdown in your git repo and submit the link on Gauchospace
Submit as a group with your partner, you will have to fill out the group select on Gauchspace first before you submit
# Assignment 5

Working in a new group



Write that function, save it in a .R file

In an Rmarkdown document, generate some data to experiment with your function, create scenario where you repeat the function for each row in a data set (you can use this for inputs and/or parameters) - Similar to what we did for the autopower function when we ran it for multiple speeds (but you could do something over time, multiple climate inputs, multiple ages...depending on your function of course)

Then generate a scenario where you repeat what you just did (for all rows) where you vary another a parameter using pmap (or a loop) - Similar to what we did when we  ran our autopower function for different cars and speeds - and then repeated the cars/speed scenarios for different drag coefficients

Make sure you use good programming practices
* provide details on the function contract at the top of the function - what are inputs/output their units format etc
* understandable variables names
* commenting through out so its easy to understand what you are doing
* add error checking


# Review for next class

* DataTypes.Rmd
* compute_simpson_index.R
* computediversity.R
