---
title: "Before next class"

---

# <span style="color:orange"> PART 1: Finish writing a function from class </span>


One of the equations used to compute automobile fuel efficiency is as follows this is the power required to keep a car moving at a given speed is as follows:


$Pb = crolling * m *g *V + \frac{1}{2} * A*p_{air}*c_{drag}*V^3$


where crolling and cdrag are rolling and aerodynamic resistive coefficients, typical values are 0.015 and 0.3, respectively.

- V: is vehicle speed (assuming no headwind) in m/s (or mps) m: is vehicle mass in kg

- A is surface area of car $(m^2)$

- *g*: is acceleration due to gravity $(9.8 m/s^2 )$ 

- p_air = density of air $(1.2kg/m^3 )$

- Pb is power in Watts

1. Write a function to compute power, given a truck of m=31752 kg (parameters for a heavy truck) for a range of different highway speeds, The surface area of this truck  is 16 $m^2$

* 30 m/s
* 80 km/hr
* 120 km/hr
* 40 km/hr
* 5 km/hr


2. Plot power as a function of speed

3. Recompute for a lighter vehicle (15,000 kg) 
Add a second line to your graph for lighter vehicle

* Keep your function in its own file, store it in a subdirectory called *R* and then create a **separate** Rmarkdown document to use the function and store the Rmarkdown in a different directory

You don't need to hand in anything - but you need to complete this exercise before next class because
we will build on these skills

# <span style="color:orange"> PART 2: Review Two Rmarkdowns </span>

Before next class, review these two Rmarkdowns in 
https://github.com/naomitague/ESM_262_Examples

If you've already cloned this, you will find them in the Rmarkdown subdirectory

* Sampling_example.Rmd
* Error_checking.Rmd

