---
title: "Course resources - Lecture 2"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Assignment 2 - To Submit


With your group, think of an example program that you might want to design that is complex enough to involve several modules

* write a contract for the overall program (input, output, parameters)
* break the program in to modules (naming them appropriately), wrate a contract for each one
* create a diagram that shows how these modules would be put together to go from inputs to output for the overall program (you can use whatever tools you like to create this)

* summarize this in an Rmarkdown document

*  select a group member and use their group repository 

-  <span style="color: maroon;">Add the link to your remote repository and name of this Rmarkdown file on Gauchospace as GROUP submission for Assignment 1b </span>

# Review for class

Review **starting_functions.Rmd** 
To access this file, go to the following github repo

[Example/Review Repo](https://github.com/naomitague/ESM_262_Examples.git)

- find and go through *Rmarkdown/starting_functions.Rmd* BEFORE next class - play with it; come ready to ask questions in class

  - you can either *clone* this repository or just download the file - it is in rhe **Rmarkdown** directory
  - cloning will make it easier for you to get future files (by pulling) but...
  - if you **clone** make sure this is in a completely separate directory from your assignments directory (git doesn't like two different repos in the same place!)
  

Next class we will use this to learn how to make a function in R

