---
title: 'Assignment '
---


# Assignment 

For this assignment work in *pairs* - and submit as a group

* Design a function - you can pick any subject and you can even make up the equations as long as they conceptually make sense
  * Make sure it has at least 2 inputs and 1 parameter (ideally more) and at least 2 outputs
  * Code your function in R, save as a R file in subdirectory called R
  * Make sure you include documentation (both at the top as we've shown in past examples, and inline)
  * Include some error checking

* In an Rmarkdown file, generate some data for 2 of the function inputs
  * use a *for*  loop to run the function for the data
  * repeat the "looping" using something from the "purrr" package 
  * Graph results (you can decide what the most interesting way to graph - you just need to make one graph)

* Write at least 2 tests for your function; store in a separate test file

* Put this in a git repo that includes an R subdirectory a tests subsdirectory and an Rmarkdown file and submit the link on Gauchospace (or you can put all of this in a new git repo or a subdirectory of an existing git repo)

Submit the link to repo (and name of subdirectory if part of a larger git project) as a group with your partner,

You will have to fill out the group select on Gauchospace first before you submit

*Grading Rubric*

* Created a function 
  * at least 2 inputs, 1 parameter and 2 outputs (it can have more) (5pts)
  * includes error checking (5 pts)


* Rmarkdown that generates test data and runs the function
  * data generation ( 5pts)
  * run function multiple times with a loop (5 pts)
  * run function multiple times with something from *purr* (pmap) (5pts)
  * Graphs results (5 pts)

* Test file
  * a file with two tests (10pts)

Good programming practices (10 pts)
Total 50pts

Also review spring_summary.R and tests of that function from 
[ESM_262_Examples](https://github.com/naomitague/ESM_262_Examples)
