---
title: "Course resources - Lecture 1"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Assignment for next class

 Create R project for this course that is linked to git


 - Review how Git and Github works if needed (see links below for help)
 - Create two directories - working and assignments
 - In the assignments directory, create an **Rmarkdown** file
    * add one paragraph that describes why you are taking this course
    * add one paragraph that describes your data science background
- Commit change to local and  remote github repository

-  <span style="color: maroon;">Add the link to your remote repository on Gauchospace as submission for Assignment 1a </span>
- Make sure that Naomi and Louis have access (if it is a private repository, add **naomitague** and **LouisGraup** as collaborators)

If you run into roadblocks here - send Louis and Naomi an email and we will try to set a time for a tutorial on setting things up


## R Installation


So that we all are working with the same code make sure you have a recent version of

 * **R  (4.0.3 )**

 * **RStudio (1.3.1093)** installed,

 You will also need the following libraries to get started

    **tidyverse**
    **devtools**
    **purr**


## Git Help


**GitHub**

From ESM  206 you already have a GitHub account, but if not
    [request a GitHub account](https://github.com/join).



- There is a lot of information on the web that you can use to refresh / learn to take advantage of **Git** . This one is pretty much all you need to know for this course

- [Happy Git and GitHub for the useR](http://happygitwithr.com/)


If you need more help with Git let us know and we will set a time for a tutorial :)

